### ISSUE TITLE
Fastd und L2TP-Broker parallel betreiben

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/Ansible-Freifunk-Gateway#80]
In der Domänenliste sollen folgende Einträge möglich sein:

```
   "25":
      dhcp_start: 10.25.64.0
      dhcp_ende: 10.25.127.255
      server_id: 2
      partner: "automatix"
      fastd: {true|false}
      l2tp: {true|false}
```

Wobei L2TP standardmäßig true ist, wenn es nicht gesetzt ist und Fastd standardmäßig false ist.

**Comment by MPW1412** [comment]
@citronalco, das wäre unser Vorschlag, wie man das sauber mit Variablen steuert. Was hältst du davon?

**Comment by MPW1412** [comment]
Notiz an uns: Beim Implementieren darauf achten, dass es ggfs. auch wieder Rückgebaut wird.

**Comment by citronalco** [comment]
Kann man so machen. Ich habe nur die kleine Befürchtung, dass es zu Verwirrung führt wenn "fastd" und "l2tp" unterschiedliche Standardwerte haben.

Andere Idee: Ich kenne eurer Einsatzszenario nicht im Detail, aber ich denke dass man die eingesetzten Tunneltechniken eigentlich nur an der Domäne und nicht für jede Domäne an jedem Server einzeln festmachen will. Dann wäre es sinnvoll, das global in "domaenen" festzulegen, z.B. so:
```
domaenen:
  "01":
    name: Münster-Mitte-Süd
    community: Münster
    vpn:
      - tunneldigger
      - fastd
    ffv4_network: 10.1.0.0/16
    ffv6_network: 2a03:2260:115:100::/64
    [...]
```
Wir werden vorerst nur eine Domäne haben, und da wahrscheinlich l2tp und fastd anbieten. Der Overhead, auf einem Server L2TP und  fastd laufen zu haben dürfte auch vernachlässigbar sein. Trotzdem wäre es schön das gelöst zu haben - niemand weiß was die Zukunft bringt und wer das hier sonst noch nutzt.
